name: Unit tests

on: [pull_request]

jobs:
  run:

    runs-on: ubuntu-latest

    strategy:
      matrix:        
        php-versions: ['7.3', '7.4', '8.0']
        phpunit-versions: ['latest']
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Unit Test PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: mbstring, intl
        ini-values: post_max_size=256M, max_execution_time=180
        coverage: xdebug        
        tools: php-cs-fixer, phpunit:${{ matrix.phpunit-versions }}, composer:v1
    - run: composer install
    - run: composer test